"""initial migration

Revision ID: 9298c0c015c8
Revises: d2841812ed9e
Create Date: 2024-10-14 13:23:30.805866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9298c0c015c8'
down_revision = 'd2841812ed9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
